### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by rmmilewi** [morpheus-project/morpheus#20]
Hi! Pardon the intrusion. My name is Reed, and I'm a software engineering researcher at Sandia National Laboratories in the US. I've created an issue on your repo just to ask a quick question. If you don't have time or don't care to respond, feel free to ignore me and/or delete this issue.

Where I work, we have a very diverse ecosystem of cutting-edge research codes spanning every discipline you could imagine. I'm part of our software engineering research department, and it's our job to keep that ecosystem robust and healthy. Part of that means helping scientists to adopt good software practices. Right now, my mind has been on software versioning/release schemes (e.g. semantic versioning). 

In order to build a case for/against getting my people on-board with the practice, I figured I should ask people who already use versioning to release their software to see what they think. So I gathered up a list of scientific software repositories on GitHub, then I selected those that tracked versioned releases, that were reasonably active, etc.  Finally, I picked a handful of those repos and decided to reach out to them. Morpheus ended up on that list.

Anyway, here's the question:

> What do you believe are the benefits (or drawbacks) of having versioned releases of your software (i.e. 1.0.0, 1.1.0, 2.0.0...)? When should someone start thinking about versioning/releasing their code?

Just a sentence or two, that's all I need. For context, imagine the preceding sentence is this: "_But don't just take my word for it, just listen to what this accomplished-researcher-working-on-AI-for-astronomical-data-analysis has to say!_".

Thank you so much!

Reed Milewicz
rmilewi@sandia.gov

**Comment by ryanhausen** [comment]
Hi Reed!

Thanks for reaching out. Here are my thoughts, for what they are worth.

>What do you believe are the benefits (or drawbacks) of having versioned releases of your software (i.e. 1.0.0, 1.1.0, 2.0.0...)? 

In my opinion, versioning does two things. First, it makes me think about the roadmap for the project. For example, deciding what the minimum viable product for the project is. Second, it advertises to users how stable/complete the project is. 

>When should someone start thinking about versioning/releasing their code?

This probably varies by project, but I think versioning should be considered as soon as there is more than one person involved with the code on the project, whether that's contributors or users. I think that you can release your software as soon as it's versioned. The stability/completeness of the project is advertised in the version number.

I hope this helps. Feel free to reach out if you want to discuss this more.

Ryan Hausen
rhausen@ucsc.edu

**Comment by rmmilewi** [comment]
Fantastic! Yes, that's great. Exactly the sort of thing that I was looking for. 

Thank you for taking the time to respond! You've been very helpful. :-)

**Comment by ryanhausen** [comment]
You're welcome!
