### ISSUE TITLE
Use morpheus with different number/different bands than just H, J, Z, and V

### ISSUE THREAD

**Issue by igorkolesnikov13** [morpheus-project/morpheus#26]
Hi Ryan,

Is it possible to use morpheus with different number/different bands than just H, J, Z, and V.
For example, I'm working with SDSS  and have ugriz (mainly working just with r).

If not, in your opinion, how complicated it would be to implement this?

**Comment by ryanhausen** [comment]
Howdy,

The input to the model requires four bands and I am not sure how well it would perform using different bands then those it was trained on. You could try it out and see what the results look like.

You may also run into issues with the difference in pixel scales between the SDSS and GOODS image. I think that the CANDELS data is ~0.06arcsec/pixel and SDSS appears to be ~0.39arcsec/pixel. The difference in resolution makes me think that you'll probably see a lot of ps/compact predicted sources.

If the performance isn't that good the next best step would be to train a version of morpheus using the r band only. To train another model could be a little involved. You could use the labels that were released with the paper if there is shared area of the sky between SDSS and GOODS. 

I'd be happy to help you get things working.

**Comment by igorkolesnikov13** [comment]
Thanks for the fast reply.
Well, the point is, that we are working with galaxy morphometry (CAS system with some additional parameters). One of the problems that we're having is figuring out how to properly segment the image in such a way, that we can preserve spiral arms in spiral galaxies and do not introduce too much noise in case of ellipticals. Up until now, we were using sExtractor and tweaking threshold (k).

So I was thinking about DL segmentation.

**Comment by ryanhausen** [comment]
I see, well if you don't need the morphology specifically then it might work out. The easiest thing to try would be using the r band stacked four times. If not you might need a model trained on your data.
